### ISSUE TITLE
?remember - generic key/value storage

### ISSUE THREAD

**Issue by thxo** [classabbyamp/discord-qrm2#191]
**Sure, a user story**
As a witty, senior member of a Discord server, I want to be able to quickly provide newcomers with information using shortcuts so I don't have to look for them every time.

**Describe the solution you'd like**
A command to store arbitrary key-value things, like commonly-distributed links. An example workflow may look like this:

```
> ?remember cab somebody "https://www.youtube.com/watch?v=eT3BFzSD6YY is a great song"
Bot: I will remember the alias "somebody".

> ?remember
Bot: https://www.youtube.com/watch?v=eT3BFzSD6YY is a great song
```

**Describe alternatives you've considered**
@cschmittiey was originally thinking about querying against an arbitrary Wiki or website for frequently-asked questions, but it might be better to generalize it as a generic key/value storage.

**Comment by classabbyamp** [comment]
hmmm I'm more inclined to *not* maintain some sort of runtime database, especially because this would require maintaining that runtime state when restarting the bot (not optimal).

Once we see how the wiki works it may be possible to `?wiki <search terms>` and return either an existing page or a search results page, similar to DuckDuckGo's bang search for wikipedia, which uses the search URL. Wikipedia will redirect to the proper page if the search terms match, and otherwise will show results.

**Comment by 0x5c** [comment]
Having a `?tag` command in YARC's discord server would be nice, but if it were to be added to a bot, it won't be this one.

That would require maintaining a DB with the bot, which would go against the basis for qrm: a simple bot to provide ham-related functionality.

**Comment by 0x5c** [comment]
Related/moved: #192
